import { createEmptyPromptProject } from './promptFactory'
import type { PromptTemplate } from '../types/models'

export const promptTemplates: PromptTemplate[] = [
  {
    id: 'cyberpunk-rain',
    title: 'Cyberpunk Rainy Street',
    description: 'Neon reflections, wet asphalt and cinematic solitude.',
    profileValues: {
      subjectType: 'traveler',
      weather: 'soft rain',
      timeOfDay: 'midnight',
      mood: 'mysterious',
      style: 'cinematic concept art',
      lighting: 'neon reflections',
      composition: 'wide cinematic frame',
    },
    project: {
      ...createEmptyPromptProject('image'),
      title: 'Cyberpunk Rainy Street',
      subject: {
        type: 'lone courier',
        description: 'hooded figure',
        action: 'standing under a flickering sign',
      },
      environment: {
        location: 'dense Osaka side street',
        weather: 'warm rain and reflective puddles',
        timeOfDay: 'midnight',
        era: 'near future',
      },
      mood: 'lonely but electric',
      style: 'high-detail cinematic concept art',
      lighting: 'neon reflections with soft atmospheric haze',
      composition: 'wide frame with strong leading lines',
      details: ['steam rising from vents', 'passing holographic ads'],
      tags: ['cyberpunk', 'rain', 'cinematic'],
    },
  },
  {
    id: 'dark-fantasy-castle',
    title: 'Dark Fantasy Castle',
    description: 'A mythic fortress wrapped in fog and old dread.',
    profileValues: {
      subjectType: 'warrior',
      weather: 'fog',
      timeOfDay: 'night',
      mood: 'oppressive',
      style: 'dark fantasy matte painting',
      lighting: 'moonlight',
      composition: 'low angle',
    },
    project: {
      ...createEmptyPromptProject('image'),
      title: 'Dark Fantasy Castle',
      subject: {
        type: 'weathered knight',
        description: 'cloaked silhouette',
        action: 'climbing a broken stairway',
      },
      environment: {
        location: 'ancient castle carved into a cliff',
        weather: 'rolling fog',
        timeOfDay: 'dusk',
        season: 'late autumn',
      },
      mood: 'ominous and sacred',
      style: 'dark fantasy matte painting',
      lighting: 'cold moonlight crossing torch smoke',
      composition: 'towering vertical composition',
      details: ['tattered banners', 'ravens circling the battlements'],
      tags: ['dark fantasy', 'castle'],
    },
  },
  {
    id: 'cozy-cottage',
    title: 'Cozy Cottage',
    description: 'Warm domestic quietness in a handmade world.',
    profileValues: {
      subjectType: 'architectural landmark',
      weather: 'snowfall',
      timeOfDay: 'blue hour',
      mood: 'serene',
      style: 'storybook illustration',
      lighting: 'warm window glow',
      composition: 'layered foreground and background',
    },
    project: {
      ...createEmptyPromptProject('image'),
      title: 'Cozy Cottage',
      subject: {
        type: 'small cottage',
        description: 'handcrafted countryside home',
      },
      environment: {
        location: 'forest clearing',
        season: 'early winter',
        weather: 'light snowfall',
        timeOfDay: 'blue hour',
      },
      mood: 'serene and welcoming',
      style: 'storybook illustration',
      lighting: 'warm window glow against cool evening air',
      composition: 'three-quarter view with foreground foliage',
      details: ['smoke curling from the chimney', 'lantern by the wooden door'],
      tags: ['cozy', 'cottage'],
    },
  },
  {
    id: 'anime-portrait',
    title: 'Anime Portrait',
    description: 'Focused character design with emotional clarity.',
    profileValues: {
      subjectType: 'portrait',
      weather: '',
      timeOfDay: 'golden hour',
      mood: 'hopeful',
      style: 'anime key visual',
      lighting: 'dramatic backlight',
      composition: 'close-up portrait',
    },
    project: {
      ...createEmptyPromptProject('image'),
      title: 'Anime Portrait',
      subject: {
        type: 'young heroine',
        appearance: 'windswept hair and expressive eyes',
        action: 'looking just beyond the viewer',
      },
      environment: {
        location: 'soft abstract background with petals',
        timeOfDay: 'sunset',
      },
      mood: 'hopeful and bittersweet',
      style: 'anime key visual',
      lighting: 'warm backlight with luminous edge highlights',
      composition: 'close-up portrait with shallow depth of field',
      details: ['floating petals', 'subtle fabric movement'],
      tags: ['anime', 'portrait'],
    },
  },
  {
    id: 'dystopian-video',
    title: 'Cinematic Dystopian Alley',
    description: 'Single-shot motion prompt for gritty urban atmosphere.',
    profileValues: {
      subjectType: 'traveler',
      weather: 'storm',
      timeOfDay: 'night',
      mood: 'tense',
      style: 'single-take film still',
      lighting: 'dramatic backlight',
      shotType: 'wide shot',
      movement: 'slow push-in',
      lensFeel: '35mm cinematic lens',
    },
    project: {
      ...createEmptyPromptProject('video'),
      title: 'Cinematic Dystopian Alley',
      medium: 'video',
      subject: {
        type: 'scavenger',
        description: 'ragged survivor with improvised tech gear',
        action: 'walking cautiously through the alley',
      },
      environment: {
        location: 'dystopian alley with exposed cables and puddles',
        weather: 'light acid rain',
        timeOfDay: 'night',
      },
      mood: 'tense and cinematic',
      style: 'gritty dystopian film still',
      lighting: 'cold industrial practicals with occasional neon leaks',
      composition: 'medium tracking shot',
      details: ['faint sirens in the distance', 'sparks from damaged wiring'],
      motion: {
        subjectMotion: 'measured forward steps',
        environmentMotion: 'rain streaking through light',
        motionIntensity: 'moderate',
        rhythm: 'steady',
      },
      camera: {
        shotType: 'single-shot medium frame',
        angle: 'slightly low angle',
        movement: 'slow push-in',
        lensFeel: '35mm cinematic lens',
      },
      temporalStructure: {
        startState: 'the alley feels empty',
        progression: 'small signs of danger begin to emerge',
        endState: 'the character disappears into deeper shadow',
        durationFeel: 'brief but immersive',
      },
      tags: ['video', 'dystopian'],
    },
  },
]
